// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RAPC9Y__SOF__2023241.Data;

#nullable disable

namespace RAPC9Y__SOF__2023241.Migrations
{
    [DbContext(typeof(LoLDbContext))]
    [Migration("20240105151934_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RAPC9Y_SOF_2023241.MVC.Models.Champion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("Release")
                        .HasColumnType("int");

                    b.Property<string>("Resources")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Champions");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Gender = "Male",
                            Name = "Aatrox",
                            RegionId = 8,
                            Release = 2013,
                            Resources = "Manaless",
                            Species = "Darkin"
                        },
                        new
                        {
                            Id = "2",
                            Gender = "Female",
                            Name = "Ahri",
                            RegionId = 4,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "Vastayan"
                        },
                        new
                        {
                            Id = "3",
                            Gender = "Female",
                            Name = "Akali",
                            RegionId = 4,
                            Release = 2010,
                            Resources = "Energy",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "4",
                            Gender = "Male",
                            Name = "Akshan",
                            RegionId = 10,
                            Release = 2021,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "5",
                            Gender = "Male",
                            Name = "Alistar",
                            RegionId = 8,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Minotaur"
                        },
                        new
                        {
                            Id = "6",
                            Gender = "Male",
                            Name = "Amumu",
                            RegionId = 10,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Yordle"
                        },
                        new
                        {
                            Id = "7",
                            Gender = "Female",
                            Name = "Anivia",
                            RegionId = 12,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "God"
                        },
                        new
                        {
                            Id = "8",
                            Gender = "Female",
                            Name = "Annie",
                            RegionId = 8,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "9",
                            Gender = "Male",
                            Name = "Aphelios",
                            RegionId = 11,
                            Release = 2019,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "10",
                            Gender = "Female",
                            Name = "Ashe",
                            RegionId = 12,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "11",
                            Gender = "Male",
                            Name = "Aurelion Sol",
                            RegionId = 11,
                            Release = 2016,
                            Resources = "Mana",
                            Species = "Celestial"
                        },
                        new
                        {
                            Id = "12",
                            Gender = "Male",
                            Name = "Azir",
                            RegionId = 10,
                            Release = 2014,
                            Resources = "Mana",
                            Species = "God"
                        },
                        new
                        {
                            Id = "13",
                            Gender = "Male",
                            Name = "Bard",
                            RegionId = 8,
                            Release = 2015,
                            Resources = "Mana",
                            Species = "Celestial"
                        },
                        new
                        {
                            Id = "14",
                            Gender = "Female",
                            Name = "Bel'Veth",
                            RegionId = 13,
                            Release = 2022,
                            Resources = "Manaless",
                            Species = "Void-Being"
                        },
                        new
                        {
                            Id = "15",
                            Gender = "Other",
                            Name = "Blitzcrank",
                            RegionId = 14,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Golem"
                        },
                        new
                        {
                            Id = "16",
                            Gender = "Male",
                            Name = "Brand",
                            RegionId = 8,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "17",
                            Gender = "Male",
                            Name = "Braum",
                            RegionId = 12,
                            Release = 2014,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "18",
                            Gender = "Female",
                            Name = "Caitlyn",
                            RegionId = 7,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "19",
                            Gender = "Female",
                            Name = "Camille",
                            RegionId = 7,
                            Release = 2016,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "20",
                            Gender = "Female",
                            Name = "Cassiopeia",
                            RegionId = 6,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "21",
                            Gender = "Male",
                            Name = "Cho'Gath",
                            RegionId = 13,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Void-Being"
                        },
                        new
                        {
                            Id = "22",
                            Gender = "Male",
                            Name = "Corki",
                            RegionId = 1,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Yordle"
                        },
                        new
                        {
                            Id = "23",
                            Gender = "Male",
                            Name = "Darius",
                            RegionId = 6,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "24",
                            Gender = "Female",
                            Name = "Diana",
                            RegionId = 11,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "25",
                            Gender = "Male",
                            Name = "Dr.Mundo",
                            RegionId = 14,
                            Release = 2009,
                            Resources = "Health",
                            Species = "Chemically Altered"
                        },
                        new
                        {
                            Id = "26",
                            Gender = "Male",
                            Name = "Draven",
                            RegionId = 6,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "27",
                            Gender = "Male",
                            Name = "Ekko",
                            RegionId = 14,
                            Release = 2015,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "28",
                            Gender = "Female",
                            Name = "Elise",
                            RegionId = 9,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "29",
                            Gender = "Female",
                            Name = "Evelynn",
                            RegionId = 8,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Demon"
                        },
                        new
                        {
                            Id = "30",
                            Gender = "Male",
                            Name = "Ezreal",
                            RegionId = 7,
                            Release = 2010,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "31",
                            Gender = "Other",
                            Name = "Fiddlesticks",
                            RegionId = 8,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Demon"
                        },
                        new
                        {
                            Id = "32",
                            Gender = "Female",
                            Name = "Fiora",
                            RegionId = 3,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "33",
                            Gender = "Male",
                            Name = "Fizz",
                            RegionId = 2,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "Yordle"
                        },
                        new
                        {
                            Id = "34",
                            Gender = "Male",
                            Name = "Galio",
                            RegionId = 3,
                            Release = 2010,
                            Resources = "Mana",
                            Species = "Golem"
                        },
                        new
                        {
                            Id = "35",
                            Gender = "Male",
                            Name = "Gangplank",
                            RegionId = 2,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "36",
                            Gender = "Male",
                            Name = "Garen",
                            RegionId = 3,
                            Release = 2010,
                            Resources = "Manaless",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "37",
                            Gender = "Male",
                            Name = "Gnar",
                            RegionId = 12,
                            Release = 2014,
                            Resources = "Rage",
                            Species = "Yordle"
                        },
                        new
                        {
                            Id = "38",
                            Gender = "Male",
                            Name = "Gragas",
                            RegionId = 12,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "39",
                            Gender = "Male",
                            Name = "Graves",
                            RegionId = 2,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "40",
                            Gender = "Female",
                            Name = "Gwen",
                            RegionId = 9,
                            Release = 2021,
                            Resources = "Mana",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "41",
                            Gender = "Male",
                            Name = "Hecarim",
                            RegionId = 9,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Undead"
                        },
                        new
                        {
                            Id = "42",
                            Gender = "Male",
                            Name = "Heimerdinger",
                            RegionId = 7,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Yordle"
                        },
                        new
                        {
                            Id = "43",
                            Gender = "Female",
                            Name = "Illaoi",
                            RegionId = 2,
                            Release = 2015,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "44",
                            Gender = "Female",
                            Name = "Irelia",
                            RegionId = 4,
                            Release = 2010,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "45",
                            Gender = "Male",
                            Name = "IV.Jarvan",
                            RegionId = 3,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "46",
                            Gender = "Male",
                            Name = "Ivern",
                            RegionId = 4,
                            Release = 2016,
                            Resources = "Mana",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "47",
                            Gender = "Female",
                            Name = "Janna",
                            RegionId = 10,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "God"
                        },
                        new
                        {
                            Id = "48",
                            Gender = "Male",
                            Name = "Jax",
                            RegionId = 8,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Unknown"
                        },
                        new
                        {
                            Id = "49",
                            Gender = "Male",
                            Name = "Jayce",
                            RegionId = 7,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "50",
                            Gender = "Male",
                            Name = "Jhin",
                            RegionId = 4,
                            Release = 2016,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "51",
                            Gender = "Female",
                            Name = "Jinx",
                            RegionId = 14,
                            Release = 2013,
                            Resources = "Mana",
                            Species = "Chemically Altered"
                        },
                        new
                        {
                            Id = "52",
                            Gender = "Female",
                            Name = "Kai'Sa",
                            RegionId = 13,
                            Release = 2018,
                            Resources = "Mana",
                            Species = "Void-Being"
                        },
                        new
                        {
                            Id = "53",
                            Gender = "Female",
                            Name = "Kalista",
                            RegionId = 9,
                            Release = 2014,
                            Resources = "Mana",
                            Species = "Undead"
                        },
                        new
                        {
                            Id = "54",
                            Gender = "Female",
                            Name = "Karma",
                            RegionId = 4,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "55",
                            Gender = "Male",
                            Name = "Karthus",
                            RegionId = 9,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Undead"
                        },
                        new
                        {
                            Id = "56",
                            Gender = "Male",
                            Name = "Kassadin",
                            RegionId = 13,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Void-Being"
                        },
                        new
                        {
                            Id = "57",
                            Gender = "Female",
                            Name = "Katarina",
                            RegionId = 6,
                            Release = 2009,
                            Resources = "Manaless",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "58",
                            Gender = "Female",
                            Name = "Kayle",
                            RegionId = 3,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "59",
                            Gender = "Male",
                            Name = "Kayn",
                            RegionId = 8,
                            Release = 2017,
                            Resources = "Mana",
                            Species = "Darkin"
                        },
                        new
                        {
                            Id = "60",
                            Gender = "Male",
                            Name = "Kennen",
                            RegionId = 4,
                            Release = 2010,
                            Resources = "Energy",
                            Species = "Yordle"
                        },
                        new
                        {
                            Id = "61",
                            Gender = "Male",
                            Name = "Kha'Zix",
                            RegionId = 13,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Void-Being"
                        },
                        new
                        {
                            Id = "62",
                            Gender = "Other",
                            Name = "Kindred",
                            RegionId = 8,
                            Release = 2015,
                            Resources = "Mana",
                            Species = "God"
                        },
                        new
                        {
                            Id = "63",
                            Gender = "Male",
                            Name = "Kled",
                            RegionId = 6,
                            Release = 2016,
                            Resources = "Courage",
                            Species = "Yordle"
                        },
                        new
                        {
                            Id = "64",
                            Gender = "Male",
                            Name = "Kog'Maw",
                            RegionId = 13,
                            Release = 2010,
                            Resources = "Mana",
                            Species = "Void-Being"
                        },
                        new
                        {
                            Id = "65",
                            Gender = "Femlae",
                            Name = "LeBlanc",
                            RegionId = 6,
                            Release = 2010,
                            Resources = "Mana",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "66",
                            Gender = "Male",
                            Name = "Lee Sin",
                            RegionId = 4,
                            Release = 2011,
                            Resources = "Energy",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "67",
                            Gender = "Female",
                            Name = "Leona",
                            RegionId = 11,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "68",
                            Gender = "Female",
                            Name = "Lillia",
                            RegionId = 4,
                            Release = 2020,
                            Resources = "Mana",
                            Species = "Spirit"
                        },
                        new
                        {
                            Id = "69",
                            Gender = "Female",
                            Name = "Lissandra",
                            RegionId = 12,
                            Release = 2013,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "70",
                            Gender = "Male",
                            Name = "Lucian",
                            RegionId = 3,
                            Release = 2013,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "71",
                            Gender = "Female",
                            Name = "Lulu",
                            RegionId = 1,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Yordle"
                        },
                        new
                        {
                            Id = "72",
                            Gender = "Female",
                            Name = "Lux",
                            RegionId = 3,
                            Release = 2010,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "73",
                            Gender = "Male",
                            Name = "Malphite",
                            RegionId = 10,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Golem"
                        },
                        new
                        {
                            Id = "74",
                            Gender = "Male",
                            Name = "Malzahar",
                            RegionId = 13,
                            Release = 2010,
                            Resources = "Mana",
                            Species = "Void-Being"
                        },
                        new
                        {
                            Id = "75",
                            Gender = "Male",
                            Name = "Maokai",
                            RegionId = 9,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Spirit"
                        },
                        new
                        {
                            Id = "76",
                            Gender = "Male",
                            Name = "Master Yi",
                            RegionId = 4,
                            Release = 2010,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "77",
                            Gender = "Female",
                            Name = "Miss Fortune",
                            RegionId = 2,
                            Release = 2010,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "78",
                            Gender = "Male",
                            Name = "Mordekaiser",
                            RegionId = 6,
                            Release = 2010,
                            Resources = "Shield",
                            Species = "Revenant"
                        },
                        new
                        {
                            Id = "79",
                            Gender = "Female",
                            Name = "Morgana",
                            RegionId = 3,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "80",
                            Gender = "Female",
                            Name = "Nami",
                            RegionId = 8,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Vastayan"
                        },
                        new
                        {
                            Id = "81",
                            Gender = "Male",
                            Name = "Nasus",
                            RegionId = 10,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "God"
                        },
                        new
                        {
                            Id = "82",
                            Gender = "Male",
                            Name = "Nautilus",
                            RegionId = 2,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Revenant"
                        },
                        new
                        {
                            Id = "83",
                            Gender = "Female",
                            Name = "Neeko",
                            RegionId = 5,
                            Release = 2018,
                            Resources = "Mana",
                            Species = "Vastayan"
                        },
                        new
                        {
                            Id = "84",
                            Gender = "Female",
                            Name = "Nidalee",
                            RegionId = 8,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Vastayan"
                        },
                        new
                        {
                            Id = "85",
                            Gender = "Female",
                            Name = "Nilah",
                            RegionId = 2,
                            Release = 2022,
                            Resources = "Mana",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "86",
                            Gender = "Male",
                            Name = "Nocturne",
                            RegionId = 8,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "Demon"
                        },
                        new
                        {
                            Id = "87",
                            Gender = "Male",
                            Name = "Nunu & Willump",
                            RegionId = 12,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "88",
                            Gender = "Male",
                            Name = "Olaf",
                            RegionId = 12,
                            Release = 2010,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "89",
                            Gender = "Female",
                            Name = "Orianna",
                            RegionId = 7,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "Golem"
                        },
                        new
                        {
                            Id = "90",
                            Gender = "Male",
                            Name = "Ornn",
                            RegionId = 12,
                            Release = 2017,
                            Resources = "Mana",
                            Species = "God"
                        },
                        new
                        {
                            Id = "91",
                            Gender = "Male",
                            Name = "Pantheon",
                            RegionId = 11,
                            Release = 2010,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "92",
                            Gender = "Male",
                            Name = "Poppy",
                            RegionId = 3,
                            Release = 2010,
                            Resources = "Mana",
                            Species = "Yordle"
                        },
                        new
                        {
                            Id = "93",
                            Gender = "Male",
                            Name = "Pyke",
                            RegionId = 2,
                            Release = 2018,
                            Resources = "Mana",
                            Species = "Revenant"
                        },
                        new
                        {
                            Id = "94",
                            Gender = "Female",
                            Name = "Qiyana",
                            RegionId = 5,
                            Release = 2019,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "95",
                            Gender = "Female",
                            Name = "Quinn",
                            RegionId = 3,
                            Release = 2013,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "96",
                            Gender = "Male",
                            Name = "Rakan",
                            RegionId = 4,
                            Release = 2017,
                            Resources = "Mana",
                            Species = "Vastayan"
                        },
                        new
                        {
                            Id = "97",
                            Gender = "Male",
                            Name = "Rammus",
                            RegionId = 10,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "God"
                        },
                        new
                        {
                            Id = "98",
                            Gender = "Female",
                            Name = "Rek'Sai",
                            RegionId = 13,
                            Release = 2014,
                            Resources = "Rage",
                            Species = "Void-Being"
                        },
                        new
                        {
                            Id = "99",
                            Gender = "Female",
                            Name = "Rell",
                            RegionId = 6,
                            Release = 2013,
                            Resources = "Mana",
                            Species = "Magivally Altered"
                        },
                        new
                        {
                            Id = "100",
                            Gender = "Female",
                            Name = "Renata Glasc",
                            RegionId = 14,
                            Release = 2022,
                            Resources = "Mana",
                            Species = "Chemically Altered"
                        },
                        new
                        {
                            Id = "101",
                            Gender = "Male",
                            Name = "Renekton",
                            RegionId = 10,
                            Release = 2011,
                            Resources = "Fury",
                            Species = "God"
                        },
                        new
                        {
                            Id = "102",
                            Gender = "Male",
                            Name = "Rengar",
                            RegionId = 5,
                            Release = 2012,
                            Resources = "Ferocity",
                            Species = "Vastayan"
                        },
                        new
                        {
                            Id = "103",
                            Gender = "Female",
                            Name = "Riven",
                            RegionId = 4,
                            Release = 2011,
                            Resources = "Manaless",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "104",
                            Gender = "Male",
                            Name = "Rumble",
                            RegionId = 1,
                            Release = 2011,
                            Resources = "Heat",
                            Species = "Yordle"
                        },
                        new
                        {
                            Id = "105",
                            Gender = "Male",
                            Name = "Ryze",
                            RegionId = 8,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "106",
                            Gender = "Female",
                            Name = "Samira",
                            RegionId = 6,
                            Release = 2020,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "107",
                            Gender = "Female",
                            Name = "Sejuani",
                            RegionId = 12,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "108",
                            Gender = "Female",
                            Name = "Senna",
                            RegionId = 3,
                            Release = 2019,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "109",
                            Gender = "Female",
                            Name = "Seraphine",
                            RegionId = 7,
                            Release = 2020,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "110",
                            Gender = "Male",
                            Name = "Sett",
                            RegionId = 4,
                            Release = 2020,
                            Resources = "Grit",
                            Species = "Vastayan"
                        },
                        new
                        {
                            Id = "111",
                            Gender = "Male",
                            Name = "Shaco",
                            RegionId = 8,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Spirit"
                        },
                        new
                        {
                            Id = "112",
                            Gender = "Male",
                            Name = "Shen",
                            RegionId = 4,
                            Release = 2010,
                            Resources = "Energy",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "113",
                            Gender = "Female",
                            Name = "Shyvana",
                            RegionId = 3,
                            Release = 2011,
                            Resources = "Fury",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "114",
                            Gender = "Male",
                            Name = "Singed",
                            RegionId = 14,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Chemically Altered"
                        },
                        new
                        {
                            Id = "115",
                            Gender = "Male",
                            Name = "Sion",
                            RegionId = 6,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Revenant"
                        },
                        new
                        {
                            Id = "116",
                            Gender = "Female",
                            Name = "Sivir",
                            RegionId = 10,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "117",
                            Gender = "Male",
                            Name = "Skarner",
                            RegionId = 10,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "Brackern"
                        },
                        new
                        {
                            Id = "118",
                            Gender = "Female",
                            Name = "Sona",
                            RegionId = 8,
                            Release = 2013,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "119",
                            Gender = "Female",
                            Name = "Soraka",
                            RegionId = 11,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Celestial"
                        },
                        new
                        {
                            Id = "120",
                            Gender = "Male",
                            Name = "Swain",
                            RegionId = 6,
                            Release = 2010,
                            Resources = "Mana",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "121",
                            Gender = "Male",
                            Name = "Sylas",
                            RegionId = 3,
                            Release = 2019,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "122",
                            Gender = "Female",
                            Name = "Syndra",
                            RegionId = 4,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "123",
                            Gender = "Male",
                            Name = "Tahm Kech",
                            RegionId = 2,
                            Release = 2015,
                            Resources = "Mana",
                            Species = "Demon"
                        },
                        new
                        {
                            Id = "124",
                            Gender = "Female",
                            Name = "Taliyah",
                            RegionId = 10,
                            Release = 2016,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "125",
                            Gender = "Male",
                            Name = "Talon",
                            RegionId = 6,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "126",
                            Gender = "Male",
                            Name = "Taric",
                            RegionId = 11,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "127",
                            Gender = "Male",
                            Name = "Teemo",
                            RegionId = 1,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Yordle"
                        },
                        new
                        {
                            Id = "128",
                            Gender = "Male",
                            Name = "Thresh",
                            RegionId = 9,
                            Release = 2013,
                            Resources = "Mana",
                            Species = "Undead"
                        },
                        new
                        {
                            Id = "129",
                            Gender = "Female",
                            Name = "Tristana",
                            RegionId = 1,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Yordle"
                        },
                        new
                        {
                            Id = "130",
                            Gender = "Male",
                            Name = "Trundle",
                            RegionId = 12,
                            Release = 2010,
                            Resources = "Mana",
                            Species = "Troll"
                        },
                        new
                        {
                            Id = "131",
                            Gender = "Male",
                            Name = "Tryndamere",
                            RegionId = 12,
                            Release = 2009,
                            Resources = "Fury",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "132",
                            Gender = "Male",
                            Name = "Twisted Fate",
                            RegionId = 2,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "133",
                            Gender = "Male",
                            Name = "Twitch",
                            RegionId = 14,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Chemically Altered"
                        },
                        new
                        {
                            Id = "134",
                            Gender = "Male",
                            Name = "Udyr",
                            RegionId = 12,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Vastayan"
                        },
                        new
                        {
                            Id = "135",
                            Gender = "Male",
                            Name = "Urgot",
                            RegionId = 6,
                            Release = 2010,
                            Resources = "Mana",
                            Species = "Chemically Altered"
                        },
                        new
                        {
                            Id = "136",
                            Gender = "Male",
                            Name = "Varus",
                            RegionId = 8,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Darkin"
                        },
                        new
                        {
                            Id = "137",
                            Gender = "Female",
                            Name = "Vayne",
                            RegionId = 3,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "138",
                            Gender = "Male",
                            Name = "Veigar",
                            RegionId = 1,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Yordle"
                        },
                        new
                        {
                            Id = "139",
                            Gender = "Male",
                            Name = "Vel'Koz",
                            RegionId = 13,
                            Release = 2014,
                            Resources = "Mana",
                            Species = "Void-Being"
                        },
                        new
                        {
                            Id = "140",
                            Gender = "Female",
                            Name = "Vex",
                            RegionId = 9,
                            Release = 2021,
                            Resources = "Mana",
                            Species = "Yordle"
                        },
                        new
                        {
                            Id = "141",
                            Gender = "Female",
                            Name = "Vi",
                            RegionId = 14,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "142",
                            Gender = "Male",
                            Name = "Viego",
                            RegionId = 9,
                            Release = 2021,
                            Resources = "Manaless",
                            Species = "Undead"
                        },
                        new
                        {
                            Id = "143",
                            Gender = "Male",
                            Name = "Viktor",
                            RegionId = 14,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "144",
                            Gender = "Male",
                            Name = "Vladimir",
                            RegionId = 6,
                            Release = 2010,
                            Resources = "Bloodthirst",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "145",
                            Gender = "Male",
                            Name = "Volibear",
                            RegionId = 12,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "God"
                        },
                        new
                        {
                            Id = "146",
                            Gender = "Male",
                            Name = "Warwick",
                            RegionId = 14,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Chemically Altered"
                        },
                        new
                        {
                            Id = "147",
                            Gender = "Male",
                            Name = "Wukong",
                            RegionId = 4,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "Vastayan"
                        },
                        new
                        {
                            Id = "148",
                            Gender = "Female",
                            Name = "Xayah",
                            RegionId = 4,
                            Release = 2017,
                            Resources = "Mana",
                            Species = "Vastayan"
                        },
                        new
                        {
                            Id = "149",
                            Gender = "Male",
                            Name = "Xerath",
                            RegionId = 10,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "God"
                        },
                        new
                        {
                            Id = "150",
                            Gender = "Male",
                            Name = "Xin Zhao",
                            RegionId = 3,
                            Release = 2010,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "151",
                            Gender = "Male",
                            Name = "Yasuo",
                            RegionId = 4,
                            Release = 2013,
                            Resources = "Flow",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "152",
                            Gender = "Male",
                            Name = "Yone",
                            RegionId = 4,
                            Release = 2020,
                            Resources = "Manaless",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "153",
                            Gender = "Male",
                            Name = "Yorick",
                            RegionId = 9,
                            Release = 2011,
                            Resources = "Mana",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "154",
                            Gender = "Female",
                            Name = "Yuumi",
                            RegionId = 1,
                            Release = 2019,
                            Resources = "Mana",
                            Species = "Magically Altered"
                        },
                        new
                        {
                            Id = "155",
                            Gender = "Male",
                            Name = "Zac",
                            RegionId = 14,
                            Release = 2013,
                            Resources = "Health",
                            Species = "Golem"
                        },
                        new
                        {
                            Id = "156",
                            Gender = "Male",
                            Name = "Zed",
                            RegionId = 4,
                            Release = 2012,
                            Resources = "Energy",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "157",
                            Gender = "Female",
                            Name = "Zeri",
                            RegionId = 14,
                            Release = 2022,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "158",
                            Gender = "Male",
                            Name = "Ziggs",
                            RegionId = 7,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Yordle"
                        },
                        new
                        {
                            Id = "159",
                            Gender = "Male",
                            Name = "Zilean",
                            RegionId = 8,
                            Release = 2009,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "160",
                            Gender = "Female",
                            Name = "Zoe",
                            RegionId = 11,
                            Release = 2017,
                            Resources = "Mana",
                            Species = "Human"
                        },
                        new
                        {
                            Id = "161",
                            Gender = "Other",
                            Name = "Zyra",
                            RegionId = 5,
                            Release = 2012,
                            Resources = "Mana",
                            Species = "Unknown"
                        });
                });

            modelBuilder.Entity("RAPC9Y_SOF_2023241.MVC.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RegionName = "Bandle-City"
                        },
                        new
                        {
                            Id = 2,
                            RegionName = "Bilgewater"
                        },
                        new
                        {
                            Id = 3,
                            RegionName = "Demacia"
                        },
                        new
                        {
                            Id = 4,
                            RegionName = "Ionia"
                        },
                        new
                        {
                            Id = 5,
                            RegionName = "Ixtal"
                        },
                        new
                        {
                            Id = 6,
                            RegionName = "Noxus"
                        },
                        new
                        {
                            Id = 7,
                            RegionName = "Piltover"
                        },
                        new
                        {
                            Id = 8,
                            RegionName = "Runeterra"
                        },
                        new
                        {
                            Id = 9,
                            RegionName = "Shadow Isles"
                        },
                        new
                        {
                            Id = 10,
                            RegionName = "Shurima"
                        },
                        new
                        {
                            Id = 11,
                            RegionName = "Targon"
                        },
                        new
                        {
                            Id = 12,
                            RegionName = "Freljord"
                        },
                        new
                        {
                            Id = 13,
                            RegionName = "Void"
                        },
                        new
                        {
                            Id = 14,
                            RegionName = "Zaun"
                        });
                });

            modelBuilder.Entity("RAPC9Y_SOF_2023241.MVC.Models.SiteUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("SiteUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RAPC9Y_SOF_2023241.MVC.Models.Champion", b =>
                {
                    b.HasOne("RAPC9Y_SOF_2023241.MVC.Models.Region", "Region")
                        .WithMany("ChampionsByRegions")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("RAPC9Y_SOF_2023241.MVC.Models.Region", b =>
                {
                    b.Navigation("ChampionsByRegions");
                });
#pragma warning restore 612, 618
        }
    }
}
